### ISSUE TITLE
Handover of GO-CAM API

### ISSUE THREAD

**Issue by cmungall** [geneontology/web-gocam#16]
serverless, api gateway

currently on USC AWS account

**Comment by cmungall** [comment]
decided on call - will move to main GO AWS

**Comment by lpalbou** [comment]
Well for the go cam site yes, for the api it’s a little more complicated but possible too. Let’s delay that one until the API discussion ?

**Comment by kltm** [comment]
Talking to @sierra-moxon and @cmungall a little, here is a little more of a (super-ish--additional tickets can be added or spun out as needed) outline. Driving this would be @sierra-moxon and @lpalbou . Also noting that this API is what drives the ribbon; other uses and notes for this API can be added here or the documentation in the repo.

- [ ] Document the current setup/deployment for the GO API into https://github.com/geneontology/biolink-api 
- [ ] Document the current development workflow for the GO API into https://github.com/geneontology/biolink-api 
- [ ] Document the current troubleshooting workflow for the GO API into https://github.com/geneontology/biolink-api 
- [ ] @sierra-moxon , working with @lpalbou , to apply the documentation to setup a test instance of the API in the GO AWS environment under a test domain
- [ ] Once tested, switch over the DNS to the test instance

Ideally, this would be done uniformly, with Ubuntu-based Docker images and EC2, and turnkey deployment scripts (i.e. Ansible), yadda yadda. But time is short and we all have a lot to do, so iIf something else needs to be done for the sake of expediency or other considerations, we can revisit later on.

**Comment by kltm** [comment]
Talking with @cmungall , we were thinking of having @dustine32 and @tmushayahama take the lead on this (combined with #15
).

- [ ] Document the dataflow, development, and deployment for the /go-cam page and used APIs in public repo
- [ ] @dustine32 and @tmushayahama , working with @lpalbou , to apply the documentation to setup a test instance of the /go-cam page and services in an AWS environment under a test domain

**Comment by lpalbou** [comment]
The GO-CAM site and API are kind of two different beasts.

The GO-CAM site is extremely easy to deploy as it's just a static site html + JS + css. Last time we discussed, we were supposed to deploy it on the BBOP AWS, as @kltm you have access to the domain name and could easily register it as gocam.geneontology.org, something more proper than geneontology.cloud. The second option, if we have time (and time is starting to be scarce) is to create the browsing as a web component with @tmushayahama . It would take an afternoon, but this needs to be planified/scheduled.

The GO-CAM API however, is more integrated to AWS because of the CI/CD and because of its serverless nature (API Gateway -> AWS Lambda -> GO SPARQL endpoint). It was however build thanks to a SAM script (a serverless template, simpler than cloud formation) so it could be deployed in theory on another AWS account if needed. I would say in the interest of time, especially as the goal will be to deprecate the API to have only one.. Indeed @tmushayahama and @dustine32 could be in charge of it. But I believe for the GO-CAM site, having @kltm would be more beneficial (eg access to go domain name)

**Comment by lpalbou** [comment]
Update from August 6: @dustine32 and @sierra-moxon for transfer.

Notes: 
* serverless architecture handled with SAM, see https://github.com/geneontology/api-gorest/blob/master/template.yml
* discuss the CI/CD (eg code build, code deploy, code pipeline) that enable the API to auto-relaunch after a code change
* do an example to change a SPARQL query and observe the redeploy

**Comment by kltm** [comment]
After discussion, @dustine32 will start on knowledge transfer/docs. Later on we may call on @sujaypatil96 to help review the docs and work with @dustine32 and @sierra-moxon on exercising docs and looking at migration (TBD).

**Comment by dustine32** [comment]
I feel good about being trained on this, given that the current architecture is documented and I have access to all components in AWS.
